# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yt_pytubefix_log_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(777, 669)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_log_level = QtWidgets.QLabel(Dialog)
        self.label_log_level.setObjectName("label_log_level")
        self.horizontalLayout.addWidget(self.label_log_level)
        self.comboBox_log_level = QtWidgets.QComboBox(Dialog)
        self.comboBox_log_level.setObjectName("comboBox_log_level")
        self.horizontalLayout.addWidget(self.comboBox_log_level)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_log_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_log_clear.setObjectName("pushButton_log_clear")
        self.horizontalLayout.addWidget(self.pushButton_log_clear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_log = QtWidgets.QGroupBox(Dialog)
        self.groupBox_log.setObjectName("groupBox_log")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_log)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_log)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.groupBox_log)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_log_level.setText(_translate("Dialog", "Log Level"))
        self.pushButton_log_clear.setText(_translate("Dialog", "Clear"))
        self.groupBox_log.setTitle(_translate("Dialog", "Log File: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
